---
- name: ensure nova compute packages and dependencies are installed
  apt: 
    pkg: "{{ item }}"
    state: latest 
    update_cache: yes 
    cache_valid_time: 600
  with_items:
    - "{{ openstack_compute_package }}"
    - neutron-common
    - neutron-plugin-ml2
    - neutron-plugin-openvswitch-agent

- name: ensure nova compute is started and enabled
  service: 
    name: "{{ item }}"
    state: started 
    enabled: yes
  with_items:
    - nova-compute
    - openvswitch-switch
