---
- name: gather os specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution|lower }}-{{ 
              ansible_distribution_version }}.yml"
        - "{{ ansible_distribution|lower }}-{{ 
              ansible_distribution_release }}.yml"
        - "{{ ansible_distribution|lower }}-{{ 
              ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution|lower }}.yml"
        - "{{ ansible_os_family|lower }}.yml"
        - defaults.yml
      paths:
        - ../vars

- name: ensure openstack compute requirements packages are installed
  action: "{{ openstack_compute_package_info.pkg_mgr }}"
  args: openstack_compute_package_info.args
  with_items: openstack_compute_package_info.pre_pkgs
  when: openstack_compute_package_info.pre_pkgs|length > 0

- name: ensure sysctl is appropriately configured
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    - { name: net.ipv4.ip_forward, value: 1 }
    - { name: net.ipv4.conf.all.rp_filter, value: 0 }
    - { name: net.ipv4.conf.default.rp_filter, value: 0 }

- name: ensure openstack repository is enabled
  action: "{{ openstack_compute_repo_info.pkg_repo }}"
  args: openstack_compute_repo_info.args
  with_items: openstack_compute_repo_info.repos
  when: openstack_compute_repo_info.repos|length > 0

- name: ensure openstack compute packages are installed
  action: "{{ openstack_compute_package_info.pkg_mgr }}"
  args: openstack_compute_package_info.args
  with_items: openstack_compute_package_info.pkgs
  when: openstack_compute_package_info.pkgs|length > 0

- name: ensure required links are in place
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    force: yes
  with_items: openstack_compute_links
  when: openstack_compute_links|length > 0

- name: ensure compute required services are started and enabled
  service: 
    name: "{{ item }}"
    state: started 
    enabled: yes
  with_items: openstack_compute_required_services
  when: openstack_compute_required_services|length > 0

- name: ensure that openvswitch integration bridge exists
  openvswitch_bridge:
    bridge: br-int
    state: present
 
- name: ensure nova.conf is properly configured
  ini_file:
    dest: /etc/nova/nova.conf
    group: nova
    mode: 0640
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - { section: DEFAULT,
        option: verbose, value: "{{ openstack_log_verbose }}" }
    - { section: DEFAULT, option: debug, value: "{{ openstack_log_debug }}" }
    - { section: DEFAULT, option: log_dir, value: /var/log/nova }
    - { section: DEFAULT, option: rpc_backend, value: rabbit }
    - { section: DEFAULT,
        option: rabbit_host, value: "{{ openstack_rabbitmq_host }}" }
    - { section: DEFAULT,
        option: rabbit_hosts, value: "{{ openstack_rabbitmq_host }}" }
    - { section: DEFAULT, option: rabbit_port,
        value: "{{ openstack_rabbitmq_port }}" }
    - { section: DEFAULT, option: rabbit_userid, value: nova }
    - { section: DEFAULT, option: rabbit_password,
        value: "{{ openstack_rabbitmq_nova_password }}" }
    - { section: DEFAULT, option: rabbit_virtual_host, value: /nova }
    - { section: DEFAULT, option: glance_host,
        value: "{{ openstack_image_endpoint_host }}" }
    - { section: DEFAULT, option: my_ip,
        value: "{{ openstack_compute_node_ip }}" }
    - { section: DEFAULT, option: vnc_enabled, value: true }
    - { section: DEFAULT, option: vncserver_listen,
        value: "{{ openstack_vncserver_bind_address }}" }
    - { section: DEFAULT, option: vncserver_proxyclient_address,
        value: "{{ openstack_compute_node_ip }}" }
    - { section: DEFAULT, option: novncproxy_base_url,
        value: "http://{{ openstack_compute_endpoint_host }}:6080/vnc_auto.html" }
    - { section: DEFAULT, option: auth_strategy, value: keystone }
    - { section: DEFAULT,
        option: network_api_class, value: nova.network.neutronv2.api.API }
    - { section: DEFAULT,
        option: neutron_url, value: "{{ openstack_network_internal_url }}" }
    - { section: DEFAULT, option: neutron_auth_strategy, value: keystone }
    - { section: DEFAULT, option: neutron_admin_tenant_name, value: service }
    - { section: DEFAULT, option: neutron_admin_username, value: neutron }
    - { section: DEFAULT, option: neutron_admin_password,
        value: "{{ openstack_identity_neutron_password }}" }
    - { section: DEFAULT, option: neutron_admin_auth_url,
        value: "{{ openstack_identity_internal_url }}" }
    - { section: DEFAULT, option: linuxnet_interface_driver,
        value: nova.network.linux_net.LinuxOVSInterfaceDriver }
    - { section: DEFAULT,
        option: firewall_driver, value: nova.virt.firewall.NoopFirewallDriver }
    - { section: DEFAULT, option: security_group_api, value: neutron }
    - { section: database, option: connection,
        value: "mysql://nova:{{ openstack_mysql_nova_password }}@{{
                  openstack_mysql_host }}:{{ openstack_mysql_port }}/nova" }
    - { section: keystone_authtoken,
        option: auth_uri, value: "{{ openstack_identity_internal_url }}" }
    - { section: keystone_authtoken, option: auth_host,
        value: "{{ openstack_identity_endpoint_host }}" }
    - { section: keystone_authtoken, option: auth_port, value: 35357 }
    - { section: keystone_authtoken, option: auth_protocol, value: http }
    - { section: keystone_authtoken, option: admin_tenant_name, value: service }
    - { section: keystone_authtoken, option: admin_user, value: nova }
    - { section: keystone_authtoken, option: admin_password,
        value: "{{ openstack_identity_nova_password }}" } 
  register: modify_nova_conf

- name: ensure nova-compute.conf is properly configured
  ini_file:
    dest: /etc/nova/nova-compute.conf
    group: nova
    mode: 0640
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - { section: libvirt,
        option: virt_type, value: "{{ openstack_compute_virt_type }}" }
  register: modify_nova_compute_conf

- name: restart compute nova services if necessary
  service: 
    name: "{{ item }}"
    state: restarted 
  with_items: openstack_compute_nova_services
  when: nova_user_mod|changed or
        modify_nova_conf|changed or
        modify_nova_compute_conf|changed

- name: ensure neutron.conf is properly configured
  ini_file:
    dest: /etc/neutron/neutron.conf
    group: neutron
    mode: 0640
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - { section: DEFAULT, option: verbose, value: "{{ openstack_log_verbose }}" }
    - { section: DEFAULT, option: debug, value: "{{ openstack_log_debug }}" }
    - { section: DEFAULT, option: log_dir, value: /var/log/neutron }
    - { section: DEFAULT,
        option: rpc_backend, value: neutron.openstack.common.rpc.impl_kombu }
    - { section: DEFAULT,
        option: rabbit_host, value: "{{ openstack_rabbitmq_host }}" }
    - { section: DEFAULT,
        option: rabbit_hosts, value: "{{ openstack_rabbitmq_host }}" }
    - { section: DEFAULT,
        option: rabbit_port, value: "{{ openstack_rabbitmq_port }}" }
    - { section: DEFAULT, option: rabbit_userid, value: neutron }
    - { section: DEFAULT, option: rabbit_password,
        value: "{{ openstack_rabbitmq_neutron_password }}" }
    - { section: DEFAULT, option: rabbit_virtual_host, value: /neutron }
    - { section: DEFAULT, option: auth_strategy, value: keystone }
    - { section: DEFAULT, option: core_plugin, value: ml2 }
    - { section: DEFAULT, option: service_plugins, value: router }
    - { section: DEFAULT, option: allow_overlapping_ips, value: true }
    - { section: keystone_authtoken, option: auth_uri,
        value: "{{ openstack_identity_internal_url }}" }
    - { section: keystone_authtoken, option: auth_host,
        value: "{{ openstack_identity_endpoint_host }}" }
    - { section: keystone_authtoken, option: auth_port, value: 35357 }
    - { section: keystone_authtoken, option: auth_protocol, value: http }
    - { section: keystone_authtoken, option: admin_tenant_name,
        value: service }
    - { section: keystone_authtoken, option: admin_user, value: neutron }
    - { section: keystone_authtoken, option: admin_password,
        value: "{{ openstack_identity_neutron_password }}" }
  register: modify_neutron_conf

- name: ensure ml2_conf.ini is properly configured
  ini_file:
    dest: /etc/neutron/plugins/ml2/ml2_conf.ini
    group: neutron
    mode: 0640
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - { section: ml2, option: type_drivers, value: gre }
    - { section: ml2, option: tenant_network_types, value: gre }
    - { section: ml2, option: mechanism_drivers, value: openvswitch }
    - { section: ml2_type_gre, option: tunnel_id_ranges, value: "1:1000" }
    - { section: ovs, 
        option: local_ip, value: "{{ openstack_compute_node_ip }}" }
    - { section: ovs, option: tunnel_type, value: gre }
    - { section: ovs, option: enable_tunneling, value: true }
    - { section: securitygroup, option: firewall_driver,
        value: 
          neutron.agent.linux.iptables_firewall.OVSHybridIptablesFirewallDriver 
      }
    - { section: securitygroup, option: enable_security_group, value: true }
  register: modify_ml2_ini

- name: restart compute neutron services if necessary
  service: 
    name: "{{ item }}"
    state: restarted 
  with_items: openstack_compute_neutron_services
  when: modify_neutron_conf|changed or modify_ml2_ini|changed

- name: ensure nova and neutron sqlite are deleted
  file:
    dest: /var/lib/nova/{{ item }}.sqlite
    state: absent
  with_items:
    - nova
    - neutron

- name: ensure compute nova and neutron services are started and enabled
  service: 
    name: "{{ item }}"
    state: started 
    enabled: yes
  with_flattened: 
    - openstack_compute_nova_services
    - openstack_compute_neutron_services
  when: openstack_compute_nova_services|length > 0 or
        openstack_compute_neutron_services|length > 0
