---
- hosts: all
  gather_facts: True
  sudo: True
  roles:
    - { role: marklee77.docker, when: nova_compute_dockerized_deployment }

- hosts: all
  gather_facts: True
  sudo: True
  roles:
    - marklee77.mariadb
    - marklee77.rabbitmq-server
    - marklee77.keystone
    - marklee77.glance
    - marklee77.nova-controller
    - marklee77.neutron-controller
    - marklee77.neutron-network

- hosts: all
  gather_facts: True
  sudo: True
  tasks:

    - name: ensure required packages for prep are installed
      apt:
        pkg: "{{ item }}"
        state: latest
        update_cache: yes
        cache_valid_time: 600
      with_items:
        - python-mysqldb
        - python-keystoneclient
        - python-glanceclient
        - python-novaclient
        - python-neutronclient
      when: ansible_distribution == "Ubuntu"
